Update Ironbank

diff --git a/chart/scripts/eks_bootstrap_script b/chart/scripts/eks_bootstrap_script
--- a/chart/scripts/eks_bootstrap_script
+++ b/chart/scripts/eks_bootstrap_script
@@ -20,6 +20,8 @@ source "${SCRIPT_PATH}/common.sh"
 cluster_name=${CLUSTER_NAME-gitlab-cluster}
 nodes=${NUM_NODES-2}
 kubernetes_version=${CLUSTER_VERSION-1.21}
+ebs_csi_required_min_version="1.23"
+ebs_csi_role_name="AmazonEKS_EBS_CSI_DriverRole"
 region="${REGION-us-east-2}"
 node_type="${MACHINE_TYPE-m5.xlarge}"
 kubeconfig="${KUBECONFIG:-$HOME/.kube/config}"
@@ -29,7 +31,7 @@ eksctl_min_version="0.24.0"
 
 function print_help(){
   cat <<EOF
-Usage: ${0} ARGS (up|down|list|creds)
+Usage: ${0} ARGS (up|down|list|creds|add_ebs_csi_driver)
 -c NAME - Name of the cluster to use. Defaults to gitlab-cluster
 -n NODES - number of nodes to use. Defaults to 2
 -k VERSION - Kubernetes version to use. Defaults to 1.21
@@ -45,6 +47,7 @@ up - create a cluster
 down - delete a cluster
 list - display information about running clusters
 creds - download credentials and install into kubeconfig file
+add_ebs_csi_driver - install AWS EBS CSI Driver add-on
 EOF
 }
 
@@ -56,6 +59,109 @@ function do_up(){
   local node_type="${5}"
 
   eksctl create cluster --name="${cluster_name}" --nodes="${nodes}" --version="${kubernetes_version}" --region="${region}" --node-type="${node_type}"
+  warn_needs_ebs_csi_driver "${cluster_name}"
+}
+
+
+function warn_needs_ebs_csi_driver(){
+  local cluster_name="${1}"
+
+  if [ $(semver_compare "$kubernetes_version" "$ebs_csi_required_min_version") -ne -1 ]; then
+    ebs_csi_version=$(has_ebs_csi_installed "${cluster_name}")
+    if [ "${ebs_csi_version}" == "(NULL)" ]; then
+      echo "EKS Clusters >= ${ebs_csi_required_min_version} need the AWS EBS CSI Driver installed."
+      echo "Please see: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html"
+      echo "Use this script with the add_ebs_csi_driver command to install the driver."
+    fi
+  fi
+}
+
+
+function has_ebs_csi_installed(){
+  local cluster_name="${1}"
+  set +e
+  ebs_csi_version=$(aws eks describe-addon --cluster-name "${cluster_name}" --addon-name aws-ebs-csi-driver --query "addon.addonVersion" --output text 2> /dev/null)
+  status=$?
+  set -e
+  if [ $status -eq 0 ]; then
+    echo "${ebs_csi_version}"
+  elif [ $status -ne 254 ]; then
+    echo "An error occurred while running:"
+    echo "aws eks describe-addon --cluster-name ${cluster_name} --addon-name aws-ebs-csi-driver --query 'addon.addonVersion' --output text"
+    echo "Return code: ${status}"
+    exit $status
+  else
+    echo "(NULL)"
+  fi
+}
+
+function has_ebs_csi_role(){
+  set +e
+  get_role_details=$(aws iam get-role --role-name=${ebs_csi_role_name} 2> /dev/null)
+  status=$?
+  set -e
+  if [ $status -eq 0 ]; then
+    echo "${get_role_details}"
+  elif [ $status -ne 254 ]; then
+    echo "An error occurred while running aws iam get-role --role-name=${ebs_csi_role_name}."
+    echo "Return code: ${status}"
+    exit $status
+  else
+    echo "(NULL)"
+  fi
+}
+
+function aws_caller_account_id(){
+  aws sts get-caller-identity --output text --query Account;
+}
+
+function associate_iam_oidc_provider(){
+  local cluster_name="${1}"
+  local region="${2}"
+
+  echo "Associating IAM OIDC Provider"
+  # doesn't error if already exists, but will show a message
+  eksctl utils associate-iam-oidc-provider --region="${region}" --cluster="${cluster_name}" --approve
+}
+
+
+function do_ebs_csi_driver() {
+  local cluster_name="${1}"
+  local region="${2}"
+  local kubernetes_version="${3}"
+
+  account_id=$(aws_caller_account_id)
+  role_arn="arn:aws:iam::${account_id}:role/${ebs_csi_role_name}"
+
+  ebs_csi_version=$(has_ebs_csi_installed "${cluster_name}")
+  if [ "${ebs_csi_version}" != "(NULL)" ]; then
+    echo "EBS CSI Driver is already installed. Version: ${ebs_csi_version}"
+    exit 1
+  fi
+
+  # this really only fails if there's been a previous failed install
+  ebs_csi_role_details=$(has_ebs_csi_role)
+  if [ "${ebs_csi_role_details}" != "(NULL)" ]; then
+    echo "EBS CSI Driver role already present. Details:"
+    echo "${ebs_csi_role_details}"
+    exit 1
+  fi
+
+  associate_iam_oidc_provider "${cluster_name}" "${region}"
+
+  echo "Creating ebs-csi-controller-sa IAM service account"
+  eksctl create iamserviceaccount --name ebs-csi-controller-sa \
+                                  --namespace kube-system \
+                                  --cluster "${cluster_name}" \
+                                  --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
+                                  --approve \
+                                  --role-only \
+                                  --role-name "${ebs_csi_role_name}"
+
+  echo "Installing the aws-ebs-csi-driver add on"
+  eksctl create addon --name aws-ebs-csi-driver --cluster "${cluster_name}" \
+                      --service-account-role-arn "${role_arn}" --force
+
 }
 
 function do_down(){
@@ -156,6 +262,9 @@ case ${1} in
     ;;
   creds)
     do_creds "${cluster_name}" "${region}" "${kubeconfig}" "${auto_kubeconfig}" "${iam_role}"
+    ;;
+  add_ebs_csi_driver)
+    do_ebs_csi_driver "${cluster_name}" "${region}" "${kubernetes_version}"
     ;;
   *)
     print_help
